# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: pyzenblues
title: 我 Jamming，故我在
email: pyzenblues@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  自從開始學習藍調音樂後，就一直在研究即興是怎麼一回事，
  希望可以把這些知識應用在自己喜歡的電玩音樂 (Xenogears, Chrono Trigger, FF7) 上，
  享受重新編曲的感動。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: pyzenblues
google_analytics: UA-122350852-1

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima@master

# 是否顯示文章片段
show_excerpts: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

header_pages:
  - about.md
  - favorites.md
